# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2173a228e9b8f5737c18ce04c377628e6f198d1c69762c15f104ff4443077f68e22c3b02a99c4e5c6e3690d249afe4e2fc030ba2f1d11856a6639512eb937f0b

test:
  secret_key_base: 966d9d2224823e8e6897ed2844567967ea7093bbe27c507123f60be89139163eb098b82df41d8b9a668549f1d575a6ab72f985bf6fdc462cc6ce704fc767e368

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
